### ISSUE TITLE
feat: automated registration of the contract id on the DEN based on the contract code source

### ISSUE THREAD

**Issue by wkolod** [warp-contracts/sonar#32]
In order for the contract state to be evaluated on SonAr, the contract id needs to be registered on the DEN first.

It would be great to have an automated registration mechanism for contracts based on their code source. 

New contract instances using a "registered" `srcTxId` would be observed and evaluated without the need to register them manually.

**Comment by ppedziwiatr** [comment]
The D.R.E. nodes handles this automatically.
